long_term_memory:
  embedder: my_embedder_id
  reranker: my_reranker_id
  vector_graph_store: my_storage_id

sessiondb:
  uri: sqlitetest.db

vector_graph_store:
  my_storage_id:
    provider: neo4j
    config:
      uri: 'bolt://localhost:7687'
      username: neo4j
      password: <NEO4J_PASSWORD>
      force_exact_similarity_search: true

embedder:
  my_embedder_id:
    provider: "openai"
    config:
      model_name: "text-embedding-3-small"
      api_key: <OPENAI_API_KEY>

reranker:
  my_reranker_id:
    provider: "rrf-hybrid"
    config:
      reranker_ids:
        - id_ranker_id
        - bm_ranker_id
        - ce_ranker_id
  id_ranker_id:
    provider: "identity"
  bm_ranker_id:
    provider: "bm25"
  ce_ranker_id:
    provider: "cross-encoder"
    config:
      model_name: "cross-encoder/qnli-electra-base"
