# Reusable GitHub Actions workflow for building Python packages

name: Build python package

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version'
        required: false
        type: string
        default: '3.x'
      patch-version:
        description: 'Version to patch into pyproject.toml'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Patch version in pyproject.toml
        if: inputs.patch-version != ''
        run: |
          VERSION="${{ inputs.patch-version }}"
          echo "Updating pyproject.toml version to $VERSION"
          sed -i -E "s/^version = \".*\"/version = \"$VERSION\"/" pyproject.toml
          sed -i -E "s/^version = \".*\"/version = \"$VERSION\"/" packages/client/pyproject.toml
          sed -i -E "s/^version = \".*\"/version = \"$VERSION\"/" packages/server/pyproject.toml

      - name: Install dependencies and uv
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade build
          pip install uv

      - name: Build the packages with uv
        run: |
          uv build --project packages/client && uv build --project packages/server
          ls -lh dist/

      - name: Upload built distributions as artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-package-dist
          path: dist/*
