name: Lint Python code

permissions:
  contents: read

# Cancel any preceding run on the pull request after a new commit is pushed.
concurrency:
  group: ruff-lint-${{ github.event.pull_request.number || github.ref }}-${{ github.event_name }}

  # Don't cancel if running on a push to the main branch.
  cancel-in-progress: ${{ (github.event.pull_request.head.ref || github.ref) != 'refs/heads/main' }}

on:
  release:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/ruff-action@v3.5.1
      - uses: astral-sh/ruff-action@v3.5.1
        with:
          args: "format --check --diff"

  ty-static-check:
    name: ty static check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Test on the oldest and newest supported Python versions
        python-version: [ "3.12", "3.14" ]
    steps:
      - uses: actions/checkout@v5

      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test with python ${{ matrix.python-version }}
        run: uv run --frozen --all-extras ty check src
